# Generated by Django 5.2.8 on 2025-12-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipes',
            new_name='Equipe',
        ),
    ]
