# Generated by Django 5.2.8 on 2025-12-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0002_rename_equipes_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
